apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: REDIS_PORT
          value: "6379"
      image: jbirtharia/vote-app:latest
      name: vote-app
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 5005
          protocol: TCP