apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dep
  labels:
    name: redis-dep
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: demo-voting-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-voting-app
    spec:
      containers:
        - image: redis:latest
          name: redis-server
          ports:
            - containerPort: 6379
              protocol: TCP