apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-dep
  labels:
    name: result-app-dep
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: DB
            - name: DB_PASSWORD
              value: dbeaver
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: dbeaver
          image: jbirtharia/result-app:latest
          name: result-app
          ports:
            - containerPort: 4000
              protocol: TCP
      restartPolicy: Always