apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-node-dep
  labels:
    name: worker-node-dep
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-node-pod
      app: demo-voting-app
  template:
    metadata:
      name: worker-node-pod
      labels:
        name: worker-node-pod
        app: demo-voting-app
    spec:
      containers:
        - env:
            - name: RDS_DB_NAME
              value: DB
            - name: RDS_HOSTNAME
              value: mysql
            - name: RDS_PASSWORD
              value: dbeaver
            - name: RDS_PORT
              value: "3306"
            - name: RDS_USERNAME
              value: dbeaver
            - name: REDIS_HOSTNAME
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: jbirtharia/worker-node:latest
          name: worker-node
      restartPolicy: Always